[package]
name = "file-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["io-util", "fs"] }
tokio-stream = { version = "0.1", default-features = false, features = [
    "io-util",
] }
futures-util = "0.3"
pin-project-lite = "0.2"
log = "0.4"
