[package]
name = "file-processor-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
file-processor = { path = "../file-processor" }
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros"] }
log = "0.4"
env_logger = "0.11"
futures-util = "0.3"
serde_json = "1"
